### ISSUE TITLE
[CodeClimate] Support for ESLint 5

### ISSUE THREAD

**Issue by bdelion** [bdelion/basic-weather-app#14]
Ajout du support ESLint 5 :
To take advantage of the features it brings, you can enable the new channel on your codeclimate.yml file:
```yaml
plugins:
  eslint:
    enabled: true
    channel: eslint-5
```
